#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

// Labels every real Trash component with the recycle/refresh pictogram shipped in
// the project. Nothing on the station is disabled or replaced: this is only a
// camera-facing child above it, so dumping, triggers and NavMesh stay untouched.
public static class TrashIconSetup
{
    private const string iconName = "Recycle Icon";
    private const string oldIconName = "Trash Icon";

    private const string iconPath =
        "Assets/Layer Lab/2D Icons-PictoIconPack01/Icons/PictoIcon_512/Icon_PictoIcon_Refresh.Png";

    private static readonly Color recycleBrown = new Color(.24f, .15f, .09f, 1f);

    [MenuItem("Cooked Fast/Istasyon/Cop: Geri Donusum Ikonunu Kur", priority = 190)]
    public static void Setup()
    {
        if (EditorApplication.isPlaying)
        {
            EditorUtility.DisplayDialog("Cop Ikonu",
                "Play modundayken kurulmaz. Once oyunu durdur.", "Tamam");
            return;
        }

        // PNG may still be imported as a regular texture in a fresh checkout.
        // The same helper used by the food/tick tools changes only its importer
        // type and makes LoadAssetAtPath<Sprite> reliable.
        FoodIconBaker.MakeSprite(iconPath);

        Sprite icon = AssetDatabase.LoadAssetAtPath<Sprite>(iconPath);

        if (icon == null)
        {
            Show("Cop ikonu Sprite olarak yuklenemedi:\n" + iconPath);
            return;
        }

        Trash[] bins = Object.FindObjectsByType<Trash>(
            FindObjectsInactive.Include, FindObjectsSortMode.None);

        if (bins.Length <= 0)
        {
            Show("Acik sahnede Trash component'i olan bir obje bulunamadi.");
            return;
        }

        string report = "";
        int built = 0;

        foreach (Trash bin in bins)
        {
            if (bin == null)
                continue;

            Bounds bounds = VisualBounds(bin.transform, out bool found);

            if (!found)
            {
                report += "- " + bin.name + ": gorunur Renderer yok, atlandi\n";
                continue;
            }

            Build(bin.transform, bounds, icon);
            built++;

            report += "- " + bin.name + ": ikon " +
                      (bounds.max.y + Lift(bounds)).ToString("0.00") +
                      " dunya yuksekligine kondu\n";
        }

        if (built > 0)
            EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());

        report += "\n" + built + " cop isaretlendi.\n" +
                  "Koyu kahverengi geri donusum oklari + beyaz kenar kullanildi; acik ve koyu " +
                  "mutfak yuzeylerinde okunur.\n\n" +
                  "Sahneye bak, uygunsa Ctrl+S ile kaydet.";

        Show(report);
    }

    private static void Build(Transform host, Bounds bounds, Sprite icon)
    {
        Transform old = host.Find(iconName);

        if (old != null)
            Undo.DestroyObjectImmediate(old.gameObject);

        // Removes the bin pictogram generated by the previous version of this
        // tool, so changing the design never leaves two labels stacked.
        Transform legacy = host.Find(oldIconName);

        if (legacy != null)
            Undo.DestroyObjectImmediate(legacy.gameObject);

        GameObject root = new GameObject(iconName);

        Undo.RegisterCreatedObjectUndo(root, "Create trash icon");
        Undo.SetTransformParent(root.transform, host, "Create trash icon");

        // World placement is intentional. Trash prefabs can be rotated or have
        // scaled parents; renderer bounds are already the visible answer after
        // all of those transforms have been applied.
        root.transform.position = new Vector3(
            bounds.center.x,
            bounds.max.y + Lift(bounds),
            bounds.center.z);

        // Scene-view starting angle. FaceCamera owns it during play.
        root.transform.rotation = Quaternion.Euler(55f, 95f, 0f);

        float drawnWidth = Mathf.Max(.001f, icon.bounds.size.x);
        float stationWidth = Mathf.Max(bounds.size.x, bounds.size.z);
        float wantedWidth = Mathf.Clamp(stationWidth * .62f, .42f, .78f);
        float scale = wantedWidth / drawnWidth;

        root.transform.localScale = Vector3.one * scale;

        SpriteRenderer mark = root.AddComponent<SpriteRenderer>();

        mark.sprite = icon;
        mark.color = recycleBrown;
        mark.sortingOrder = 130;

        // The source icon is white. Tinting the main copy brown gives it the
        // kitchen palette; the separate white outline keeps the silhouette
        // readable against both the wooden floor and dark bin lid.
        SpriteOutline.Build(root, icon, mark.sortingOrder - 1, .075f);

        root.AddComponent<FaceCamera>();
    }

    private static float Lift(Bounds bounds)
    {
        return Mathf.Clamp(bounds.size.y * .16f, .16f, .32f);
    }

    private static Bounds VisualBounds(Transform root, out bool found)
    {
        Bounds result = default;
        found = false;
        Transform generated = root.Find(iconName);
        Transform legacy = root.Find(oldIconName);

        foreach (Renderer renderer in root.GetComponentsInChildren<Renderer>(true))
        {
            if (renderer == null || renderer is ParticleSystemRenderer)
                continue;

            // Re-running measures the bin, not yesterday's generated marker.
            if (generated != null && renderer.transform.IsChildOf(generated))
                continue;

            if (legacy != null && renderer.transform.IsChildOf(legacy))
                continue;

            if (!found)
            {
                result = renderer.bounds;
                found = true;
            }
            else
            {
                result.Encapsulate(renderer.bounds);
            }
        }

        return result;
    }

    private static void Show(string text)
    {
        Debug.Log("[Cop Ikonu]\n" + text);
        EditorUtility.DisplayDialog("Cop Ikonu", text, "Tamam");
    }
}
#endif
