using System.Collections;
using UnityEngine;
using UnityEngine.Rendering.Universal;
using UnityEngine.UI;

// The second player's place on the main menu.
//
// Empty it is a plus sign that opens the co-op screens. Filled it is the other
// player's animal, standing on the same line as yours -- the same 3D wardrobe
// the front menu already renders, a second time, for somebody else's choice.
//
// A real model rather than an icon, for the same reason the front menu uses one
// for you: an icon of a rabbit is a rabbit that stops matching the day somebody
// changes what a rabbit looks like.
public class CoopMateSlot : MonoBehaviour
{
    // Sixty units from the wardrobe's own stage.
    //
    // Both stages draw on the Default layer, because this project's URP
    // renderer only draws opaque geometry from a fixed layer mask and layer
    // zero is the one that is in it. So they cannot be told apart by layer and
    // are told apart by distance instead: each camera sees twenty units, and
    // sixty is comfortably more than twice that
    private static readonly Vector3 stageOrigin = new Vector3(0f, -200f, 60f);

    private const int previewLayer = 0;
    private const float previewLean = 16f;

    private static readonly int greetingState =
        Animator.StringToHash("Base Layer.Greet_Start");
    private static readonly int idleState =
        Animator.StringToHash("Base Layer.Idle");

    [Header(" Baglantilar ")]
    [Tooltip("Ana menudeki karakter vitrini. Hayvan listesi ondan aliniyor")]
    [SerializeField] private CharacterSkinPreview wardrobe;

    [Tooltip("Arti'ya basilinca acilacak online ekrani")]
    [SerializeField] private GameObject onlineScreen;

    [Header(" Parcalar ")]
    [SerializeField] private RawImage display;
    [SerializeField] private GameObject addRoot;
    [SerializeField] private Button addButton;
    [SerializeField] private Text label;

    private RenderTexture texture;
    private GameObject stage;
    private GameObject shown;
    private Camera eye;
    private Coroutine fitting;
    private int drawn = -1;

    private void Awake()
    {
        if (addButton != null)
            addButton.onClick.AddListener(Open);

        // Found rather than required. The slot is generated by a setup command
        // that may run before or after the wardrobe exists, and a null here
        // would mean an empty square with no explanation
        if (wardrobe == null)
            wardrobe = Object.FindFirstObjectByType<CharacterSkinPreview>(
                FindObjectsInactive.Include);
    }

    private void OnEnable()
    {
        Coop.Changed += Refresh;

        Refresh();
    }

    private void OnDisable()
    {
        Coop.Changed -= Refresh;

        // Torn down with the menu. This is a whole camera and a render texture
        // for a picture nobody is looking at once the game starts
        Clear();
    }

    private void Open()
    {
        if (onlineScreen != null)
            onlineScreen.SetActive(true);
    }

    // ---- what is in the square ---------------------------------------------

    private void Refresh()
    {
        bool here = Coop.MateHere && Coop.MateSkin >= 0;

        if (here && onlineScreen != null && onlineScreen.activeSelf)
        {
            // Closed the moment the other player actually arrives. Leaving the
            // room code up over the menu means the one thing they both wanted
            // to see -- each other -- is behind the screen they used to get
            // there
            onlineScreen.SetActive(false);
        }

        Switch(addRoot, !here);

        if (display != null)
            display.enabled = here;

        if (label != null)
            label.text = here ? Named(Coop.MateSkin) : "";

        if (!here)
        {
            Clear();

            return;
        }

        if (drawn == Coop.MateSkin && shown != null)
            return;

        Build();
        Show(Coop.MateSkin);
    }

    private string Named(int skin)
    {
        if (wardrobe == null)
            return "";

        string animal = wardrobe.SkinLabel(skin);

        if (string.IsNullOrEmpty(animal))
            return "";

        return GameLocalization.Get("animal." + animal.ToLowerInvariant(),
            animal.ToUpperInvariant());
    }

    // ---- the little stage ---------------------------------------------------

    private void Build()
    {
        if (stage != null)
            return;

        texture = new RenderTexture(384, 480, 24, RenderTextureFormat.ARGB32)
        {
            name = "Coop Mate Preview",
            antiAliasing = 2,
            useMipMap = false,
            autoGenerateMips = false,
        };

        texture.Create();

        if (display != null)
            display.texture = texture;

        stage = new GameObject("MENU 3D MATE STAGE");
        stage.transform.position = stageOrigin;

        GameObject holder = new GameObject("Mate Camera");

        holder.transform.SetParent(stage.transform, false);
        holder.transform.localPosition = new Vector3(0f, 1.65f, 6f);
        holder.transform.LookAt(stageOrigin + Vector3.up * 1.65f);

        eye = holder.AddComponent<Camera>();

        eye.clearFlags = CameraClearFlags.SolidColor;
        eye.backgroundColor = new Color(0f, 0f, 0f, 0f);
        eye.orthographic = true;
        eye.orthographicSize = 2.25f;
        eye.nearClipPlane = .1f;
        eye.farClipPlane = 20f;
        eye.cullingMask = 1 << previewLayer;
        eye.targetTexture = texture;
        eye.allowHDR = true;
        eye.allowMSAA = true;

        if (holder.GetComponent<UniversalAdditionalCameraData>() == null)
            holder.AddComponent<UniversalAdditionalCameraData>();

        MakeLight("Key Light", new Vector3(-2.5f, 4f, 3f),
            new Color(1f, .72f, .45f), 5f, 10f);
        MakeLight("Fill Light", new Vector3(2.5f, 2.5f, 2f),
            new Color(.35f, .65f, 1f), 2.5f, 8f);
    }

    private void MakeLight(string name, Vector3 place, Color colour,
        float intensity, float range)
    {
        GameObject host = new GameObject(name);

        host.transform.SetParent(stage.transform, false);
        host.transform.localPosition = place;

        Light light = host.AddComponent<Light>();

        light.type = LightType.Point;
        light.color = colour;
        light.intensity = intensity;
        light.range = range;

        // Ranged and masked. A point light that reached the wardrobe stage
        // would light the other player's animal twice over
        light.cullingMask = 1 << previewLayer;
        light.shadows = LightShadows.Soft;
    }

    private void Show(int skin)
    {
        if (wardrobe == null || stage == null)
            return;

        GameObject model = wardrobe.SkinModel(skin);

        if (model == null)
            return;

        if (shown != null)
            Destroy(shown);

        shown = Instantiate(model, stage.transform);
        shown.name = "Mate " + skin;
        shown.transform.localPosition = Vector3.zero;
        shown.transform.localRotation = Quaternion.Euler(previewLean, 0f, 0f);
        shown.transform.localScale = Vector3.one;

        SetLayer(shown.transform, previewLayer);

        Animator rig = shown.GetComponent<Animator>();

        if (rig == null)
            rig = shown.AddComponent<Animator>();

        if (wardrobe.SharedAvatar != null)
            rig.avatar = wardrobe.SharedAvatar;

        if (wardrobe.PreviewController != null)
            rig.runtimeAnimatorController = wardrobe.PreviewController;

        rig.applyRootMotion = false;

        // Unscaled, because the menu holds the game at zero. An animator on
        // game time in front of a paused kitchen is a statue
        rig.updateMode = AnimatorUpdateMode.UnscaledTime;
        rig.cullingMode = AnimatorCullingMode.AlwaysAnimate;
        rig.Rebind();
        rig.Update(0f);

        if (rig.runtimeAnimatorController != null)
        {
            if (rig.HasState(0, greetingState))
                rig.Play(greetingState, 0, 0f);
            else if (rig.HasState(0, idleState))
                rig.Play(idleState, 0, 0f);
        }

        drawn = skin;

        if (fitting != null)
            StopCoroutine(fitting);

        fitting = StartCoroutine(Settle(shown, rig));
    }

    // A skinned mesh does not have trustworthy bounds on the frame it was
    // instantiated, and the fit is measured off those bounds -- done too early
    // it scales the animal by whatever the last frame happened to hold
    private IEnumerator Settle(GameObject model, Animator rig)
    {
        yield return null;

        if (model == null || model != shown)
            yield break;

        rig.Update(0f);

        CharacterSkinPreview.Fit(model, rig);

        fitting = null;
    }

    private void Clear()
    {
        drawn = -1;

        if (fitting != null)
            StopCoroutine(fitting);

        fitting = null;
        shown = null;
        eye = null;

        if (stage != null)
            Destroy(stage);

        stage = null;

        if (display != null)
            display.texture = null;

        if (texture != null)
        {
            texture.Release();
            Destroy(texture);
        }

        texture = null;
    }

    private static void SetLayer(Transform root, int layer)
    {
        root.gameObject.layer = layer;

        foreach (Transform child in root)
            SetLayer(child, layer);
    }

    private static void Switch(GameObject part, bool on)
    {
        if (part != null && part.activeSelf != on)
            part.SetActive(on);
    }
}
